kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "omejdn-server.fullname" . }}-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "omejdn-server.fullname" . }}-keys
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi